// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUqA6yPO7EBUWMLDOBInW4R1DqR-5nzx8',
    appId: '1:703105549379:web:e2d7f9ef4952ba8ddf40f6',
    messagingSenderId: '703105549379',
    projectId: 'exam-159e3',
    authDomain: 'exam-159e3.firebaseapp.com',
    storageBucket: 'exam-159e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV5UmEx7AAoXgZiSY2wPTsNG_Vk1lmunw',
    appId: '1:703105549379:android:f888f69fad47b262df40f6',
    messagingSenderId: '703105549379',
    projectId: 'exam-159e3',
    storageBucket: 'exam-159e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmBZ1B-rfMWYUUdaGRFnpdfaRujgfP-9A',
    appId: '1:703105549379:ios:ae5df8d98acaead6df40f6',
    messagingSenderId: '703105549379',
    projectId: 'exam-159e3',
    storageBucket: 'exam-159e3.appspot.com',
    iosClientId: '703105549379-uv80kuntp0dq4kfgvbkcds8csa53adg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.exam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmBZ1B-rfMWYUUdaGRFnpdfaRujgfP-9A',
    appId: '1:703105549379:ios:ae5df8d98acaead6df40f6',
    messagingSenderId: '703105549379',
    projectId: 'exam-159e3',
    storageBucket: 'exam-159e3.appspot.com',
    iosClientId: '703105549379-uv80kuntp0dq4kfgvbkcds8csa53adg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.exam',
  );
}
